### ISSUE TITLE
Nullable fields in content details class for broadcast

### ISSUE THREAD

**Issue by JSBmanD** [faithoflifedev/yt#9]
There're a lot of nullable fields in model: https://developers.google.com/resources/api-libraries/documentation/youtube/v3/csharp/latest/classGoogle_1_1Apis_1_1YouTube_1_1v3_1_1Data_1_1LiveBroadcastContentDetails.html
But as I see and encounter - library doesn't have support for nullability of these fields.
<img width="572" alt="image" src="https://github.com/faithoflifedev/yt/assets/5402335/5ecb21e1-9bac-460c-b457-048b71ba5128">

**Comment by JSBmanD** [comment]
Also I can't set broadcastStatus to "active" and get 400 error. If you know what is the problem, please help

**Comment by faithoflifedev** [comment]
Resolved in the latest release - yt 2.2.5+4
